### ISSUE TITLE
Reduce verbosity of parse errors

### ISSUE THREAD

**Issue by johnsonr** [atomist-blogs/org-visualizer#159]
Parsing errors such as the following can overwhelm the output:

```
Failed to parse package-lock.json, skipping: Unexpected characters (
      },
      "dependencies": {
        "rxjs": {
          "version": "6.4.0",
...
```

**Comment by jessitron** [comment]
How do you reproduce this?

**Comment by johnsonr** [comment]
This is coming from the `parseK8sSpecFile`. I think it's trying to parse JSON as YAML.

**Comment by ddgenome** [comment]
JSON is valid YAML, so that part should be okay but I'll look into why it is failing and reducing the logging.

**Comment by ddgenome** [comment]
What are you running that is creating this output?

**Comment by ddgenome** [comment]
This appears to be an issue with yamljs. It seems it cannot handle large strings. The package is more or less dead, no releases in two years, no commits in the last year.

We use js-yaml most of the time for working with yaml. I used yamljs here because it was already being used as a dependency. I'd recommend switching to js-yaml.
